{% set name = "xraydb" %}
{% set version = "4.4.7" %}
{% set sha256 = "f133e0e1cc7d55b9d1e3fdd00ae92fe9ed7bc7ba31153b933930819627206f67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - sqlalchemy

test:
  imports:
    - xraydb
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vvvv

about:
  home: https://xraypy.github.io/XrayDB
  license: PUBLIC-DOMAIN
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: X-ray Reference Data for the Elements
  doc_url: https://xraypy.github.io/XrayDB
  dev_url: https://github.com/xraypy/XrayDB
